# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phase2.ui'
#
# Created: Sun Nov 27 15:52:06 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 629)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.transfPB = QtGui.QPushButton(self.centralwidget)
        self.transfPB.setGeometry(QtCore.QRect(350, 500, 92, 27))
        self.transfPB.setObjectName("transfPB")
        self.loadSrcPB = QtGui.QPushButton(self.centralwidget)
        self.loadSrcPB.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.loadSrcPB.setObjectName("loadSrcPB")
        self.loadTgtPB = QtGui.QPushButton(self.centralwidget)
        self.loadTgtPB.setGeometry(QtCore.QRect(410, 30, 111, 31))
        self.loadTgtPB.setObjectName("loadTgtPB")
        self.resetPB = QtGui.QPushButton(self.centralwidget)
        self.resetPB.setGeometry(QtCore.QRect(500, 500, 92, 27))
        self.resetPB.setObjectName("resetPB")
        self.savePB = QtGui.QPushButton(self.centralwidget)
        self.savePB.setGeometry(QtCore.QRect(650, 500, 92, 27))
        self.savePB.setObjectName("savePB")
        self.acqPtsPB = QtGui.QPushButton(self.centralwidget)
        self.acqPtsPB.setGeometry(QtCore.QRect(410, 370, 111, 27))
        self.acqPtsPB.setObjectName("acqPtsPB")
        self.srcGraphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.srcGraphicsView.setGeometry(QtCore.QRect(10, 80, 381, 271))
        self.srcGraphicsView.setObjectName("srcGraphicsView")
        self.tgtGraphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.tgtGraphicsView.setGeometry(QtCore.QRect(410, 80, 381, 271))
        self.tgtGraphicsView.setObjectName("tgtGraphicsView")
        self.EffectLabel = QtGui.QLabel(self.centralwidget)
        self.EffectLabel.setGeometry(QtCore.QRect(440, 430, 81, 41))
        self.EffectLabel.setObjectName("EffectLabel")
        self.tgtPt1LE = QtGui.QLineEdit(self.centralwidget)
        self.tgtPt1LE.setGeometry(QtCore.QRect(540, 370, 121, 27))
        self.tgtPt1LE.setObjectName("tgtPt1LE")
        self.tgtPt2LE = QtGui.QLineEdit(self.centralwidget)
        self.tgtPt2LE.setGeometry(QtCore.QRect(670, 370, 121, 27))
        self.tgtPt2LE.setObjectName("tgtPt2LE")
        self.tgtPt3LE = QtGui.QLineEdit(self.centralwidget)
        self.tgtPt3LE.setGeometry(QtCore.QRect(540, 400, 121, 27))
        self.tgtPt3LE.setObjectName("tgtPt3LE")
        self.tgtPt4LE = QtGui.QLineEdit(self.centralwidget)
        self.tgtPt4LE.setGeometry(QtCore.QRect(670, 400, 121, 27))
        self.tgtPt4LE.setObjectName("tgtPt4LE")
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(540, 440, 231, 27))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.acqPtsPB_extra = QtGui.QPushButton(self.centralwidget)
        self.acqPtsPB_extra.setGeometry(QtCore.QRect(10, 370, 131, 27))
        self.acqPtsPB_extra.setObjectName("acqPtsPB_extra")
        self.srcPt1LE = QtGui.QLineEdit(self.centralwidget)
        self.srcPt1LE.setGeometry(QtCore.QRect(162, 370, 131, 27))
        self.srcPt1LE.setObjectName("srcPt1LE")
        self.srcPt2LE = QtGui.QLineEdit(self.centralwidget)
        self.srcPt2LE.setGeometry(QtCore.QRect(162, 410, 131, 27))
        self.srcPt2LE.setObjectName("srcPt2LE")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.tgtPt1LE.setReadOnly(True)
        self.tgtPt2LE.setReadOnly(True)
        self.tgtPt3LE.setReadOnly(True)
        self.tgtPt4LE.setReadOnly(True)
        self.srcPt1LE.setReadOnly(True)
        self.srcPt2LE.setReadOnly(True)

        self.acqPtsPB.setCheckable(True)
        self.acqPtsPB_extra.setCheckable(True)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.transfPB.setText(QtGui.QApplication.translate("MainWindow", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSrcPB.setText(QtGui.QApplication.translate("MainWindow", "Load Source...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadTgtPB.setText(QtGui.QApplication.translate("MainWindow", "Load Target...", None, QtGui.QApplication.UnicodeUTF8))
        self.resetPB.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.savePB.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.acqPtsPB.setText(QtGui.QApplication.translate("MainWindow", "Acquire Points", None, QtGui.QApplication.UnicodeUTF8))
        self.EffectLabel.setText(QtGui.QApplication.translate("MainWindow", "Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Rotate 90", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Rotate 180", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Rotate 270", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Flip Horizontally", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Flip Vertically", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Transpose", None, QtGui.QApplication.UnicodeUTF8))
        self.acqPtsPB_extra.setText(QtGui.QApplication.translate("MainWindow", "Acquire Points", None, QtGui.QApplication.UnicodeUTF8))

